### ISSUE TITLE
Was image created with support for other OS builds?

### ISSUE THREAD

**Issue by IvanRibakov** [robinryf/docker-images#1]
I'm wondering if you have added Mac and/or Win build support when creating Unity3D image? I'm trying to use it in CI and build for Windows. Test build for Linux goes through and I get an executable out (takes around 5min to complete) but when I select `-buildWin64Player` build finishes in about a minute and there is no .exe created. No errors or other pointers to what might be going wrong in the logs either so I'm a bit in the dark and just wanted to rule out the issue of build support packages not being installed in the first place.

P.S. I am using latest docker image (2017.3)

**Comment by robinryf** [comment]
Hey Ivan,

thanks for reaching out to me. I actually haven't tried to build players yet. 😱 
I mainly use it for building asset bundles. I will look into this if I can add the required components

**Comment by IvanRibakov** [comment]
Thanks Robin, that would be awesome! Looking forward to hear about your findings! Will try to find time (and Docker skills) to follow your blog post on preparing the Unity3D image myself in the mean time.

**Comment by IvanRibakov** [comment]
I was able to install necessary components by modifying `UNITY_COMPONENTS` variable in get-unity.sh to 'Unity,Mac,Windows' in branch 2017.3.0f1. Install went fine but I'm yet to check the actual build results.

**Comment by robinryf** [comment]
Thank you for your input. I decided to include the Desktop platforms (Mac,Windows,Linux). If other platforms like mobile or console are needed a specialized tag could be introduced.

**Comment by robinryf** [comment]
Images are built and ready
