### ISSUE TITLE
Windows & Mac build support not installed on Unity2018.1.0f2

### ISSUE THREAD

**Issue by Genteure** [robinryf/docker-images#3]
The component name for Windows and Mac was `Windows` & `Mac`, but on Unity 2018 it changed to `Windows-Mono` & `Mac-Mono`. Possibly because you can use IL2CPP for Windows and Mac now, although not with Linux Editor.

![image](https://user-images.githubusercontent.com/11240579/40976666-63b4acaa-6901-11e8-9760-04f0eaf969db.png)

## Fix 1:

Change [`UNITY_COMPONENTS="Unity,Mac,Windows,Linux"` ](https://github.com/robinryf/docker-images/blob/a344618f00219cc5f7d425eda527b5056de916d7/unity3d/get-unity.sh#L6) to `UNITY_COMPONENTS="All"`

- all components are installed, maybe someone later finds out they want to build for WebGL or Android, they could just use this image without any hassle.
- build time may be longer.

## Fix 2:

Change [`UNITY_COMPONENTS="Unity,Mac,Windows,Linux"` ](https://github.com/robinryf/docker-images/blob/a344618f00219cc5f7d425eda527b5056de916d7/unity3d/get-unity.sh#L6) to `UNITY_COMPONENTS="Unity,Mac-Mono,Windows-Mono,Linux"`

- just fix the problem.

## Fix 3:

Remove the argument `--components`, install default components. All components are installed by default by the time I'm writing this.

- all components are installed just like fix 1.
- build time may be longer.
- Unity may later change the components selected by default.

**Comment by robinryf** [comment]
Hey Genteure,

thank you for the great messages! I added the build support for Mac and Windows a while ago. I did not see that the component name had changed. Thank you for the info!

I will update the files soon. I will probably go for fix 2 since I don't want to make the docker image later as it is. I was thinking about offering a bigger mobile variant. Would you use such variant?

Cheers

Robin

**Comment by Genteure** [comment]
Not in near future since I don't have a project targeting platforms other than Windows. But when I have such a project, I would love to automate the build process.

I was struggling to run Unity Personal on CI for about two weeks, if Unity [add an argument like -free](https://feedback.unity3d.com/suggestions/allow-activation-of-personal-license-through-the-command-line), it could be so much easier.

**Comment by angusmf** [comment]
Webgl would be rad.

**Comment by robinryf** [comment]
I opened issue #4 to address the missing platforms later. I will hopefully soon be able to support them

**Comment by Genteure** [comment]
Kinda off-topic for this issue but I don't think open a new issue is necessary.
There's a little problem with `run-unity.sh`, I need to run `run-unity.sh "-quit -batchmode"` instead of `run-unity.sh -quit -batchmode`.

To fix this, we need to change from
`xvfb-run -a --server-args="-screen 0 1024x768x24" /opt/Unity/Editor/Unity $1`
to 
`xvfb-run -a --server-args="-screen 0 1024x768x24" /opt/Unity/Editor/Unity $*`
(I think, not tested)

It just more comfortable to write build scripts this way.
Maybe add this as a new script file to avoid broke someone's already working CI script.

**Comment by Genteure** [comment]
I can confirm Windows build is working. Closing.
